#action name
name: Jekyll site CI with Playwright
# trigger on this event
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-site:
    runs-on: ubuntu-22.04 #vm runs on linux but should add windows and macOS for testing reasons
    
    #checkout repo into the action runner, whats makes it run for github actions
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    #setting up node js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' #doesnt matter too much but 16-20 apparently are best for playwright
       
    #install playwright
    - name: Install dependencies
      run: npm ci
    - name: install playwright browsers
      run: npx playwright install-deps
    - name: install playwright browsers no deps
      run: npx playwright install

    #- name: Install Playwright Browsers
     # uses: microsoft/playwright-github-action@v1


    #builds a container for the jekyll site using docker, this is what literally runs the site
    - name: Build Jekyll site
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    #playwright can't read html it needs an actual site to see(no pun intended), so you need to open a local http server to run the website
    - name: Start HTTP server
      run: |
        npx serve _site -l 3000 &
        sleep 10


    - name: List output HTML files
      run: ls -l _site && cat _site/index.html

    #runs the playwright tests in the repo
    - name: Run Playwright tests
      run: npx playwright test



    #uploads the report thats provided from the playwright tests
    - name: Upload test report (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report
