#action name
name: Jekyll site CI with Playwright
# trigger on this event
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-site:
    runs-on: ubuntu-22.04 #vm runs on linux but should add windows and macOS for testing reasons
    
    #checkout 
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install
        npx playwright install

    #- name: Install Playwright Browsers
     # uses: microsoft/playwright-github-action@v1
      #with:
       # with-deps: true
    - name: Run playwright tests
      run: npx playwright test

    - name: Build Jekyll site
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Start HTTP server
      run: |
        npx serve _site -l 3000 &
        sleep 3

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload test report (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report
